[package]
name = "dbus-tokio-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
dbus-tokio = "0.7.6"
futures = "0.3.28"
tokio = { version = "1.27.0", features = ["full"] }
